export const SUBJECTS = [
  'Physics',
  'Chemistry',
  'Mathematics',
  'Biology',
  'English',
  'Computer Science',
  'History',
  'Geography',
  'Economics',
  'Accountancy',
  'Business Studies',
  'Political Science',
  'Environmental Science',
  'Hindi',
  'Marathi',
  'Sociology',
  'Psychology',
  'General Knowledge',
  'Current Affairs',
  'Logical Reasoning',
  'Aptitude',
  'Art & Design',
  'Physical Education',
  'Music',
  'Home Science',
  'Language (French/German/Sanskrit)',
];

export const GOALS = [
  // Academic Exam Prep
  '12th Board Exam Prep (CBSE/State)',
  '10th Board Exam Prep',
  'JEE Mains + Advanced',
  'NEET UG',
  'CUET (UG/PG)',
  'Olympiads (Physics/Chemistry/Math/Biology)',
  'NTSE/NSO/NSTSE Preparation',
  'ICSE/ISC Final Exams',
  'State CET (MH-CET, KCET, etc.)',

  // Competitive & Skill Exams
  'Coding & Programming Practice',
  'Logical Reasoning & Aptitude Practice',
  'Quantitative Aptitude Prep',
  'SSC/Banking/Government Exam Prep',
  'UPSC/State PSC Foundation',
  'CLAT Law Entrance Prep',
  'CA Foundation Preparation',
  'Commerce Olympiad',
  'SAT/ACT Prep (for Abroad)',
  'TOEFL/IELTS English Language Prep',

  // Skill Development
  'Public Speaking & Communication',
  'Creative Writing Practice',
  'General Awareness Boost',
  'Mental Math & Speed Calculation',
  'Basic French/German Language',
  'Art & Creativity Time',
  'Meditation & Mindfulness Routine',
  'Personal Development & Motivation',

  // Career Oriented
  'Entrepreneurship Basics',
  'Finance & Stock Market Learning',
  'AI & Data Science Foundation',
  'Web Development Learning Path',
  'App Development Bootcamp',
  'Ethical Hacking & Cybersecurity Basics',
];
